name: inception

services:
        nginx:
                build: requirements/nginx
                depends_on:
                        - mariadb
                        - wordpress
                restart: always
                init: true
                container_name: nginx
                networks:
                        - inception
                ports:
                        - "443:443"
                volumes:
                        - website:/var/www/html

        mariadb:
                build:
                        context:  requirements/mariadb
                        args:
                                - DATABASE_NAME
                                - DATABASE_ADMIN
                                - DATABASE_ADMIN_PASS
                                - DATABASE_USER
                                - DATABASE_USER_PASS
                restart: always
                init: true
                container_name: mariadb
                networks:
                        - inception
                expose:
                        - "3306"
                volumes:
                        - database:/var/lib/mysql
        wordpress:
                build: requirements/wordpress
                environment:
                        - DATABASE_NAME
                        - DATABASE_ADMIN
                        - DATABASE_ADMIN_PASS
                        - URL
                        - TITLE
                        - WORDPRESS_ADMIN
                        - WORDPRESS_ADMIN_PASS
                        - WORDPRESS_ADMIN_EMAIL
                restart: always
                init: true
                depends_on:
                        - mariadb
                container_name: wordpress
                networks:
                        - inception
                expose:
                        - "9000"
                volumes:
                        - website:/var/www/html

volumes:
        database:
                name: database
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ${VOLUMES_PATH}/database
        website:
                name: website
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ${VOLUMES_PATH}/website

networks:
        inception:
