services:
        nginx:
                build: requirements/nginx/.
                container_name: nginx
                depends_on:
                        - wordpress
                        - mariadb
                ports:
                        - "443:443"
                volumes:
                        - ./web:/var/www/html
                networks:
                        inception:
        wordpress:
                build: requirements/wordpress/.
                container_name: wp-php
                depends_on:
                        - mariadb
                volumes:
                        - /home/myokogaw/data/web:/var/www/html
                networks:
                        inception:
        mariadb:
                build: requirements/mariadb/.
                env_file: ".env"
                container_name: mariadb
                volumes:
                        - /home/myokogaw/data/wp_db:/var/lib/mysql
                networks:
                        inception:

networks:
        inception:        
